- id: '1776816463721'
  alias: Auto Arm Away When Phone Leaves
  description: Arms the alarm to away mode when the Pixel 8 Pro leaves home and sends
    a mobile notification
  triggers:
  - platform: state
    entity_id: person.cherpin
    to: not_home
  conditions:
  - condition: state
    entity_id: alarm_control_panel.alarmo
    state: disarmed
  actions:
  - action: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.alarmo
  - action: notify.mobile_app_pixel_8_pro
    data:
      title: House Secured
      message: The alarm has been automatically set to Armed Away.
  mode: single
- id: '1778390547200'
  alias: Auto Lock Front Door When Armed Away
  description: Locks the front door deadbolt whenever the alarm is armed away, if
    it isn't already locked.
  triggers:
  - platform: state
    entity_id: alarm_control_panel.alarmo
    to: armed_away
  conditions:
  - condition: state
    entity_id: lock.assure_2_biometric_deadbolt
    state: unlocked
  actions:
  - action: lock.lock
    target:
      entity_id: lock.assure_2_biometric_deadbolt
  - action: notify.mobile_app_pixel_8_pro
    data:
      title: Front Door Locked
      message: The front door has been automatically locked.
  mode: single
