# Loads default set of integrations. Do not remove.
default_config:

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml
template: !include templates.yaml

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.72.0/24

homeassistant:
  external_url: https://ha.herpin.xyz
  internal_url: http://192.168.72.110:8123

prometheus:

notify:
  - name: email_alert
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: herpintech@gmail.com
    encryption: starttls
    username: herpintech@gmail.com
    password: !secret gmail_password
    recipient:
      - caleb.herpin@gmail.com
    sender_name: Home Security
