# Loads default set of integrations. Do not remove.
default_config:

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
input_number: !include input_numbers.yaml

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.72.0/24

homeassistant:
  external_url: https://ha.herpin.xyz
  internal_url: http://192.168.72.110:8123

prometheus:

# Amazon Echo example configuration.yaml entry
emulated_hue:
  listen_port: 80
  # Amazon Echo/Alexa stopped working on different ports. Search for "Philips Hue Bridge V1 (round)" in the Alexa App to discover devices.
  host_ip: 192.168.72.110
  expose_by_default: false
  entities:
    light.kitchen_main_light:
      name: "Kitchen Main Light"